export const MobileSelectors = {
    // Common sation elements valid across the app
    common: {
        homeHeader: '~mobile_navbar1_title',
        hamburgerMenu: '~mobile_navbar1_leftnavbtn_a',
    },

    // RN Style Inspector UI (Input/Output)
    inspector: {
        styleCommandInput: '~exinput_i',
        bottomsheetStyleCommandInput: '~exinput1_i',
        modalStyleCommandInput: '~exinput1_i',
        styleOutputLabel: '~label2_caption', // default (do not remove to avoid breaking other widgets)
        panelStyleOutputLabel: '(//android.widget.TextView[@content-desc="label2_caption"])[2]',
        labelStyleOutputLabel: '(//android.widget.TextView[@content-desc="label2_caption"])[2]',
        formcontrolsStyleOutputLabel: '(//android.widget.TextView[@content-desc="label2_caption"])[2]',
    },

    // Home page widget links (direct navigation)
    navItems: {
        button: '~button_link_caption',
        accordion: '~accordion_link_caption',
        panel: '~panel_link_caption',
        cards: '~cards_link_caption',
        label: '~label_link_caption',
        formcontrols: '~formc_link_caption',
        'form-wrapper': '~formc_link_caption',
        picture: '~picture_link_caption',
        carousel: '~carousel_link_caption',
        bottomsheet: '~bottomsheet_link_caption',
        barcodescanner: '~barcodescanner_link_caption',
        tabs: '~tabs_link_caption',
        tabbar: '~tabbar_link_caption',
        navbar: '~navbar_link_caption',
        list: '~list_link_caption',
        chips: '~chips_link_caption',
        radioset: '~radioset_link_caption',
        checkbox: '~checkbox_link_caption',
        checkboxset: '~checkboxset_link_caption',
        toggle: '~toggle_link_caption',
        switch: '~switch_link_caption',
        wizard: '~wizard_link_caption',
        container: '~container_link_caption',
        tile: '~tile_link_caption',
        'button-group': '~buttongroup_link_caption',
        anchor: '~anchor_link_caption',
        webview: '~webview_link_caption',
        spinner: '~spinner_link_caption',
        search: '~search_link_caption',
        'progress-bar': '~progressbar_link_caption',
        'progress-circle': '~progresscircle_link_caption',
        'dropdown-menu': '~dropdownmenu_link_caption',
        popover: '~popover_link_caption',
        login: '~login_link_caption',
        calendar: '~calendar_link_caption',
        slider: '~slider_link_caption',
        rating: '~rating_link_caption',
        icon: '~icon_link_caption',
        lottie: '~lottie_link_caption',
        audio: '~audio_link_caption',
        message: '~message_link_caption',
        modal: '~modaldialog_link_caption',
        'modal-dialog': '~modaldialog_link_caption',
        fileupload: '~fileupload_link_caption',
        currency: '~currency_link_caption',
        select: '~select_link_caption',
        'panel-footer': '~panel_link_caption',
        camera: '~camera_link_caption',
        datetime: '~datetime_link_caption',
        video: '~video_link_caption',
    },

    // Per-widget page headers (to verify we landed on the right page)
    headers: {
        // Using navbar leftnavbtn as default header selector for all widgets
        button: '~exinput_i',
        accordion: '~mobile_navbar1_leftnavbtn_a',
        panel: '~mobile_navbar1_leftnavbtn_a',
        cards: '~mobile_navbar1_leftnavbtn_a',
        label: '~mobile_navbar1_leftnavbtn_a',
        formcontrols: '~exinput_i',
        'form-wrapper': '~entestkey_i',
        picture: '~mobile_navbar1_leftnavbtn_a',
        carousel: '~mobile_navbar1_leftnavbtn_a',
        bottomsheet: '~mobile_navbar1_leftnavbtn_a',
        barcodescanner: '~mobile_navbar1_leftnavbtn_a',
        tabs: '~exinput_i',
        tabbar: '~exinput_i',
        navbar: '~mobile_navbar1_leftnavbtn_a',
        list: '~mobile_navbar1_leftnavbtn_a',
        chips: '~mobile_navbar1_leftnavbtn_a',
        radioset: '~mobile_navbar1_leftnavbtn_a',
        checkbox: '~mobile_navbar1_leftnavbtn_a',
        checkboxset: '~mobile_navbar1_leftnavbtn_a',
        toggle: '//android.widget.TextView[@text="Home"]',
        switch: '~mobile_navbar1_leftnavbtn_a',
        wizard: '//android.widget.TextView[@text="Home"]',
        container: '//android.widget.TextView[@text="Home"]',
        tile: '//android.widget.TextView[@text="Home"]',
        'button-group': '~exinput_i',
        anchor: '~exinput_i',
        webview: '//android.widget.TextView[@text="Home"]',
        spinner: '//android.widget.TextView[@text="Home"]',
        search: '//android.widget.TextView[@text="Home"]',
        'progress-bar': '//android.widget.TextView[@text="Home"]',
        'progress-circle': '//android.widget.TextView[@text="Home"]',
        'dropdown-menu': '//android.widget.TextView[@text="Home"]',
        popover: '~exinput_i',
        login: 'loggedInUserForm1_submit_formAction_a',
        calendar: '~mobile_navbar1_leftnavbtn_a',
        slider: '~mobile_navbar1_leftnavbtn_a',
        rating: '~mobile_navbar1_leftnavbtn_a',
        icon: '~mobile_navbar1_leftnavbtn_a',
        lottie: '~mobile_navbar1_leftnavbtn_a',
        audio: '~mobile_navbar1_leftnavbtn_a',
        message: '~mobile_navbar1_leftnavbtn_a',
        modal: '~exinput_i',
        'modal-dialog': '~exinput_i',
        fileupload: '~mobile_navbar1_leftnavbtn_a',
        currency: '~exinput_i',
        select: '~exinput_i',
        'panel-footer': '~mobile_navbar1_leftnavbtn_a',
        camera: '~mobile_navbar1_leftnavbtn_a',
        datetime: '~mobile_navbar1_leftnavbtn_a',
        video: '~mobile_navbar1_leftnavbtn_a',
    },
};
