export const MobileSelectors = {
    // Common sation elements valid across the app
    common: {
        homeHeader: '~mobile_navbar1_title',
        backButton: '~mobile_navbar1_backbtn_icon',
        hamburgerMenu: '~exinput_i',
    },

    // RN Style Inspector UI (Input/Output)
    inspector: {
        styleCommandInput: '~exinput_i',
        bottomsheetStyleCommandInput: '~exinput1_i',
        modalStyleCommandInput: '~exinput1_i',
        styleOutputLabel: '~label2_caption', // default (do not remove to avoid breaking other widgets)
        panelStyleOutputLabel: '~label2_caption',
        panelStyleOutputLabelIos: '(//XCUIElementTypeStaticText[@name="label2_caption"])[2]',
        bottomsheetStyleOutputLabel: '~label2_caption',
        bottomsheetStyleOutputLabelIos: '(//XCUIElementTypeStaticText[@name="label2_caption"])[2]',
        labelStyleOutputLabel: '~label2_caption',
        formcontrolsStyleOutputLabel: '~label2_caption',
        formcontrolsStyleOutputLabelIos: '(//XCUIElementTypeStaticText[@name="label2_caption"])[2]',
        tileStyleOutputLabel: '~label2_caption',
        tileStyleOutputLabelIos: '(//XCUIElementTypeStaticText[@name="label2_caption"])[2]',
        datetimeStyleOutputLabel: '~label2_caption',
        datetimeStyleOutputLabelIos: '(//XCUIElementTypeStaticText[@name="label2_caption"])[2]',
    },

    // Home page widget links (direct navigation)
    navItems: {
        button: '~button_link_caption',
        accordion: '~accordion_link_caption',
        'accordion-pane': '~accordion_link_caption',
        panel: '~panel_link_caption',
        cards: '~cards_link_caption',
        label: '~label_link_caption',
        formcontrols: '~formc_link_caption',
        'form-wrapper': '~formc_link_caption',
        picture: '~picture_link_caption',
        carousel: '~carousel_link_caption',
        bottomsheet: '~bottomsheet_link_caption',
        barcodescanner: '~barcodescanner_link_caption',
        tabs: '~tabs_link_caption',
        tabbar: '~tabbar_link_caption',
        navbar: '~navbar_link_caption',
        list: '~list_link_caption',
        chips: '~chips_link_caption',
        radioset: '~radioset_link_caption',
        checkbox: '~checkbox_link_caption',
        checkboxset: '~checkboxset_link_caption',
        toggle: '~toggle_link_caption',
        switch: '~switch_link_caption',
        wizard: '~wizard_link_caption',
        container: '~container_link_caption',
        tile: '~tile_link_caption',
        'button-group': '~buttongroup_link_caption',
        anchor: '~anchor_link_caption',
        webview: '~webview_link_caption',
        spinner: '~spinner_link_caption',
        search: '~search_link_caption',
        'progress-bar': '~progressbar_link_caption',
        'progress-circle': '~progresscircle_link_caption',
        'dropdown-menu': '~dropdownmenu_link_caption',
        popover: '~popover_link_caption',
        login: '~login_link_caption',
        calendar: '~calendar_link_caption',
        slider: '~slider_link_caption',
        rating: '~rating_link_caption',
        icon: '~icon_link_caption',
        lottie: '~lottie_link_caption',
        audio: '~audio_link_caption',
        message: '~message_link_caption',
        'modal-dialog': '~modaldialog_link_caption',
        fileupload: '~fileupload_link_caption',
        currency: '~currency_link_caption',
        select: '~select_link_caption',
        'panel-footer': '~panel_link_caption',
        camera: '~camera_link_caption',
        datetime: '~datetime_link_caption',
        video: '~video_link_caption',
    },

    // Per-widget page headers (to verify we landed on the right page)
    headers: {
        // Using navbar leftnavbtn as default header selector for all widgets
        button: '~button1_caption',
        accordion: '~accordion1_header0',
        'accordion-pane': '~accordion1_header0',
        panel: '~panel1_header_title',
        cards: '~mobile_navbar1_title',
        label: '~exinput_i',
        formcontrols: '~custom_i',
        'form-wrapper': '~entestkey_i',
        picture: '~exinput_i',
        carousel: '~exinput_i',
        bottomsheet: '~bottomsheet1_scorllview',
        barcodescanner: '~barcodescanner1_button_icon_icon',
        tabs: '~tabs1_headers_0_title',
        tabbar: '~mobile_tabbar1',
        navbar: '~mobile_navbar1_title',
        list: '~exinput_i',
        chips: '~chips1_chip0',
        radioset: '~exinput_i',
        checkbox: '~exinput_i',
        checkboxset: '~exinput_i',
        toggle: '~exinput_i',
        switch: '~exinput_i',
        wizard: '~exinput_i',
        container: '~mobile_navbar1_title',
        tile: '~exinput_i',
        'button-group': '~button1_caption',
        anchor: '~anchor1_caption',
        webview: '~exinput_i',
        spinner: '~exinput_i',
        search: '~exinput_i',
        'progress-bar': '~progress_bar1_progressbar',
        'progress-circle': '~progress_circle1_progresscircle',
        'dropdown-menu': '~exinput_i',
        popover: '~exinput_i',
        login: 'loggedInUserForm1_submit_formAction_a',
        calendar: '~exinput_i',
        slider: '~anchor1_caption',
        rating: '~exinput_i',
        icon: '~exinput_i',
        lottie: '~exinput_i',
        audio: '~exinput_i',
        message: '~message2_caption',
        'modal-dialog': '~dialog1_icon_caption',
        fileupload: '~exinput_i',
        currency: '~exinput_i',
        select: '~exinput_i',
        'panel-footer': '~panel1_header_title',
        camera: '~camera1_button_icon_icon',
        datetime: '~datetime1_l',
        video: '~exinput_i',
    },
};
